# Copyright 2017-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Auto-Generated by cargo-ebuild 0.3.1

EAPI=7

CRATES="
aho-corasick-0.7.14
ansi_term-0.11.0
ansi_term-0.12.1
anyhow-1.0.31
assert_cmd-1.0.1
atty-0.2.14
autocfg-1.0.1
bitflags-1.2.1
clap-2.33.1
difference-2.0.0
doc-comment-0.3.3
float-cmp-0.8.0
hermit-abi-0.1.13
lazy_static-1.4.0
libc-0.2.71
memchr-2.3.4
normalize-line-endings-0.3.0
num-traits-0.2.14
predicates-1.0.5
predicates-core-1.0.0
predicates-tree-1.0.0
proc-macro2-1.0.18
quote-1.0.7
regex-1.4.2
regex-syntax-0.6.21
strsim-0.8.0
syn-1.0.31
term_size-0.3.2
textwrap-0.11.0
thiserror-1.0.19
thiserror-impl-1.0.19
thread_local-1.0.1
treeline-0.1.0
unicode-width-0.1.7
unicode-xid-0.2.0
wait-timeout-0.2.0
vec_map-0.8.2
winapi-0.3.8
winapi-i686-pc-windows-gnu-0.4.0
winapi-x86_64-pc-windows-gnu-0.4.0
${P}
"

inherit cargo

DESCRIPTION="A command-line hex viewer"
HOMEPAGE="https://github.com/sharkdp/hexyl"
SRC_URI="$(cargo_crate_uris ${CRATES})"
RESTRICT="mirror"
# License set may be more restrictive as OR is not respected
# use cargo-license for a more accurate license picture
LICENSE="Apache-2.0 MIT Unlicense"
SLOT="0"
KEYWORDS="~amd64"
IUSE=""

DEPEND=""
RDEPEND=""

