# Copyright 2017-2020 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Auto-Generated by cargo-ebuild 0.3.0

EAPI=7

CRATES="
adler32-1.0.4
aes-0.3.2
aes-soft-0.3.3
aesni-0.6.0
aho-corasick-0.7.6
ansi_term-0.11.0
arrayvec-0.4.12
atty-0.2.13
autocfg-0.1.7
backtrace-0.3.40
backtrace-sys-0.1.32
base64-0.10.1
base64-0.11.0
bitfield-0.13.2
bitflags-1.2.1
block-buffer-0.7.3
block-cipher-trait-0.6.2
block-modes-0.3.3
block-padding-0.1.4
blowfish-0.4.0
buf_redux-0.8.4
byte-tools-0.3.1
byteorder-1.3.2
bytes-0.4.12
bytes-0.5.2
c2-chacha-0.2.3
cast5-0.6.0
cc-1.0.46
cfb-mode-0.3.2
cfg-if-0.1.10
chrono-0.4.9
circular-0.3.0
clap-2.33.0
clear_on_drop-0.2.3
cloudabi-0.0.3
cookie-0.12.0
cookie_store-0.7.0
core-foundation-0.6.4
core-foundation-sys-0.6.2
crc24-0.1.6
crc32fast-1.2.0
crossbeam-deque-0.7.1
crossbeam-epoch-0.7.2
crossbeam-queue-0.1.2
crossbeam-utils-0.6.6
curl-0.4.25
curl-sys-0.4.23
curve25519-dalek-2.0.0
darling-0.10.2
darling_core-0.10.2
darling_macro-0.10.2
derive_builder-0.9.0
derive_builder_core-0.9.0
des-0.3.0
digest-0.8.1
dtoa-0.4.4
ed25519-dalek-1.0.0-pre.3
either-1.5.3
encoding_rs-0.8.20
env_proxy-0.3.1
error-chain-0.12.1
failure-0.1.6
failure_derive-0.1.6
fake-simd-0.1.2
filetime-0.2.7
flate2-1.0.12
fnv-1.0.6
foreign-types-0.3.2
foreign-types-shared-0.1.1
fuchsia-cprng-0.1.1
fuchsia-zircon-0.3.3
fuchsia-zircon-sys-0.3.3
futures-0.1.29
futures-channel-0.3.1
futures-core-0.3.1
futures-cpupool-0.1.8
futures-sink-0.3.1
futures-task-0.3.1
futures-util-0.3.1
generic-array-0.12.3
getrandom-0.1.12
git-testament-0.1.7
git-testament-derive-0.1.8
h2-0.1.26
h2-0.2.1
hex-0.4.0
home-0.5.1
http-0.1.19
http-0.2.0
http-body-0.1.0
http-body-0.3.0
httparse-1.3.4
hyper-0.12.35
hyper-0.13.0
hyper-tls-0.3.2
ident_case-1.0.1
idna-0.1.5
idna-0.2.0
indexmap-1.3.0
iovec-0.1.4
itoa-0.4.4
keccak-0.1.0
kernel32-sys-0.2.2
lazy_static-1.4.0
libc-0.2.65
libm-0.2.1
libz-sys-1.0.25
lock_api-0.3.1
log-0.4.8
lzma-sys-0.1.15
matches-0.1.8
md-5-0.8.0
memchr-2.2.1
memoffset-0.5.1
mime-0.3.14
mime_guess-2.0.1
miniz_oxide-0.3.3
mio-0.6.21
miow-0.2.1
native-tls-0.2.3
net2-0.2.33
nodrop-0.1.14
nom-4.2.3
num-bigint-dig-0.6.0
num-derive-0.3.0
num-integer-0.1.41
num-iter-0.1.39
num-traits-0.2.8
num_cpus-1.10.1
opaque-debug-0.2.3
opener-0.4.1
openssl-0.10.25
openssl-probe-0.1.2
openssl-src-111.6.0+1.1.1d
openssl-sys-0.9.52
parking_lot-0.9.0
parking_lot_core-0.6.2
percent-encoding-1.0.1
percent-encoding-2.1.0
pgp-0.4.0
pin-project-0.4.6
pin-project-internal-0.4.6
pin-project-lite-0.1.1
pin-utils-0.1.0-alpha.4
pkg-config-0.3.16
ppv-lite86-0.2.6
proc-macro2-1.0.6
publicsuffix-1.5.3
pulldown-cmark-0.6.0
quote-1.0.2
rand-0.6.5
rand-0.7.2
rand_chacha-0.1.1
rand_chacha-0.2.1
rand_core-0.3.1
rand_core-0.4.2
rand_core-0.5.1
rand_hc-0.1.0
rand_hc-0.2.0
rand_isaac-0.1.1
rand_jitter-0.1.4
rand_os-0.1.3
rand_pcg-0.1.2
rand_xorshift-0.1.1
rdrand-0.4.0
redox_syscall-0.1.56
regex-1.3.1
regex-syntax-0.6.12
remove_dir_all-0.5.2
reqwest-0.9.22
retry-0.5.1
ripemd160-0.8.0
rs_tracing-1.0.1
rsa-0.2.0
rustc-demangle-0.1.16
rustc_version-0.2.3
ryu-1.0.2
safemem-0.3.3
same-file-1.0.5
schannel-0.1.16
scopeguard-1.0.0
security-framework-0.3.1
security-framework-sys-0.3.1
semver-0.9.0
semver-parser-0.7.0
serde-1.0.101
serde_derive-1.0.101
serde_json-1.0.41
serde_urlencoded-0.5.5
sha-1-0.8.1
sha2-0.8.0
sha3-0.8.2
slab-0.4.2
smallvec-0.6.10
smallvec-1.0.0
socket2-0.3.11
socks-0.3.2
spin-0.5.2
stream-cipher-0.3.2
string-0.2.1
strsim-0.8.0
strsim-0.9.2
subtle-2.2.1
syn-1.0.5
synstructure-0.12.1
tar-0.4.26
tempfile-3.1.0
term-0.5.1
textwrap-0.11.0
thread_local-0.3.6
threadpool-1.7.1
time-0.1.42
tokio-0.1.22
tokio-0.2.4
tokio-buf-0.1.1
tokio-current-thread-0.1.6
tokio-executor-0.1.8
tokio-io-0.1.12
tokio-reactor-0.1.10
tokio-sync-0.1.7
tokio-tcp-0.1.3
tokio-threadpool-0.1.16
tokio-timer-0.2.11
tokio-util-0.2.0
toml-0.5.3
tower-service-0.3.0
try-lock-0.2.2
try_from-0.3.2
twofish-0.2.0
typenum-1.11.2
unicase-2.5.1
unicode-bidi-0.3.4
unicode-normalization-0.1.8
unicode-width-0.1.6
unicode-xid-0.2.0
url-1.7.2
url-2.1.0
uuid-0.7.4
vcpkg-0.2.7
vec_map-0.8.1
version_check-0.1.5
wait-timeout-0.2.0
walkdir-2.2.9
want-0.2.0
want-0.3.0
wasi-0.7.0
winapi-0.2.8
winapi-0.3.8
winapi-build-0.1.1
winapi-i686-pc-windows-gnu-0.4.0
winapi-util-0.1.2
winapi-x86_64-pc-windows-gnu-0.4.0
winreg-0.6.2
ws2_32-sys-0.2.1
x25519-dalek-0.6.0
xattr-0.2.2
xz2-0.1.6
zeroize-1.1.0
zeroize_derive-1.0.0
"

inherit cargo bash-completion-r1

DESCRIPTION="Manage multiple rust installations with ease"
# Double check the homepage as the cargo_metadata crate
# does not provide this value so instead repository is used
HOMEPAGE="https://github.com/rust-lang/rustup.rs"
SRC_URI="https://github.com/rust-lang/rustup/archive/${PV}.tar.gz $(cargo_crate_uris ${CRATES})"
RESTRICT="mirror"
# License set may be more restrictive as OR is not respected
# use cargo-license for a more accurate license picture
LICENSE="Apache-2.0 Apache-2.0 WITH LLVM-exception BSD-2-Clause BSD-3-Clause BSL-1.0 CC0-1.0 ISC MIT Unlicense Zlib"
SLOT="0"
KEYWORDS="amd64 x86"
IUSE="bash-completion zsh-completion"

DEPEND=""
RDEPEND=""

src_install() {
	ln -s target/release/rustup-init ./rustup
	if use bash-completion; then
		./rustup completions bash > rustup.bash_completion
		dobashcomp rustup.bash_completion
	fi
	if use zsh-completion; then
		./rustup completions zsh > rustup.zsh_completion
		insinto usr/share/zsh/site-functions
		newins rustup.zsh_completion _rustup
	fi
	rm ./rustup
	dobin target/release/rustup-init
	dosym /usr/bin/rustup-init /usr/bin/rustup
}

